export const ADD_BOOK = 'ADD_BOOK';

export const DELETE_BOOK = 'DELETE_BOOK';

export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';

export const ADD_MEMBER = 'ADD_MEMBER';

export const DELETE_MEMBER = 'DELETE_MEMBER';

export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';

export const ADD_BOOK_TO_MEMBER = 'ADD_BOOK_TO_MEMBER';

export const ADD_MEMBER_TO_BOOK = 'ADD_MEMER_TO_BOOK';

export const EXTEND_DATE = 'EXTEND_DATE';

export const MEMBERSHIP_EXPIRY = 'MEMBERSHIP_EXPIRY';

export const MEMBERSHIP_RENEW = 'MEMBERSHIP_RENEW';